// Generated by https://quicktype.io

export interface CreateClub {
  nombre_club: string;
  ciudad_club: string;
  estadio_club: string;
  escudo_club: string;
  fechaFund_club: string;
  titulosPrimera_club: number;
}
